# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_4laPMTkt_8OpXE4f4PGTPO0TnPWtaY8
"""

dic = {"princesse":"\U0001F478"}
origine = ["princesse", "am", "genius"]
phrase = []
for i in range(len(origine)):
  phrase.append(0)
  n = origine[i]
  if n in dic:
    phrase[i] = dic[n]
  else:
    phrase[i] = origine[i]
  print(phrase[i],end=' ')